language: c
env:
  - ARDUINO_VERSION=1.6.13
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/TheThingsNetwork
  - arduino --install-library "DHT sensor library:1.3.0,Adafruit Unified Sensor:1.0.2"
before_script:
  # Replace placeholders with actual frequency plan (on Mac OS folow -i by '')
  - find $PWD/examples -type f -name "*.ino" -exec sed -i 's/REPLACE_ME/TTN_FP_EU868/g' {} +
script:
  - test/verify arduino:avr:leonardo examples/SendABP/SendABP.ino
  - test/verify arduino:avr:leonardo examples/DeviceInfo/DeviceInfo.ino
  - test/verify arduino:avr:leonardo examples/TheThingsMessage/Receive/Receive.ino
  - test/verify arduino:avr:leonardo examples/TheThingsMessage/Send/Send.ino
  - test/verify arduino:avr:leonardo examples/PassThrough/PassThrough.ino
  - test/verify arduino:avr:leonardo examples/QuickStart/QuickStart.ino
  - test/verify arduino:avr:leonardo examples/Receive/Receive.ino
  - test/verify arduino:avr:leonardo examples/ReceiveClassC/ReceiveClassC.ino
  - test/verify arduino:avr:leonardo examples/SendOTAA/SendOTAA.ino
  - test/verify arduino:avr:leonardo examples/Sensors/DHT/DHT.ino
  - test/verify arduino:avr:leonardo examples/Sensors/LightSensor/LightSensor.ino
  - test/verify arduino:avr:leonardo examples/Workshop/Workshop.ino
  - test/verify arduino:avr:leonardo test/TheThingsMessage/TheThingsMessage.ino
  - test/verify arduino:avr:leonardo test/TheThingsNetwork/TheThingsNetwork.ino
notifications:
  email:
    on_success: change
    on_failure: change
